name = "intg-shop"
main = "dist/_worker.js"
compatibility_date = "2023-06-05"
node_compat = true

kv_namespaces = [
    { binding = "KV_STORE", id = "6f3ba354a5e444f1b21e0093c80f6e85", preview_id = "ff086acf88b0483ca83a6bde7fe74600" }
]

[vars]
KEY_ID = "1949a2edb1cab0db98cdf67e81742982"
FUNCTION_ID_ORDER_DISCOUNT = "01H3DFRZZ4FSGBH438FGSPJZPZ"
FUNCTION_ID_PRODUCT_DISCOUNT = "01H3DFS2EPHWX7KTZR8HZADW6T"
JWK = "{\"kty\": \"EC\",\"use\": \"sig\",\"crv\": \"P-256\",\"kid\": \"0d2dbad0-81f5-4625-94a8-91e839581ac8\",\"x\": \"F4hIC9DufzIBAolcQsfOpsBEQd6Vgw5T2eci0GzuQM0\",\"y\": \"nkGBEGRI-QZ8AVztb20W2pzulUx_-jWbxiP1cgc89PY\",\"alg\": \"ES256\"}"

# The necessary secrets are:
# - KEY_SECRET
# - ADMIN_ID
# - ADMIN_SECRET
